name: Publish
on:
  pull_request:
    branches: [master]
    types:
      - closed
jobs:
  node-npm:
    if: github.event.pull_request.merged == true
    uses: kne-union/actions/.github/workflows/publish-miniprogram-libs-workflow.yml@master
    secrets: inherit
    with:
      package_name: '@kne/mini-core'
      APP_ID: wxae849489ee6c1994
      PRIVATE_KEY_NAME: KNEUNION_PRIVATE_KEY
      TOKEN_SECRET_NAME: TOKEN_SECRET_NAME


